import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'EN' | 'HI' | 'TA' | 'TE' | 'BN' | 'MR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  EN: {
    "Career GPS Engine": "Career GPS Engine",
    "Study Materials Hub": "Study Materials Hub",
    "PYQ Viewer": "PYQ Viewer",
    "Salary Predictor": "Salary Predictor",
    "Exam Directory": "Exam Directory",
    "Daily Quiz": "Daily Quiz",
    "Doubt Solver": "Doubt Solver",
    "Current Affairs": "Current Affairs",
    "Resume Rebrander": "Resume Rebrander",
    "Roadmap Visualizer": "Roadmap Visualizer",
    "Eligibility Checker": "Eligibility Checker",
    "Personal Vault": "Personal Vault",
    "Toggle Dark Mode": "Toggle Dark Mode",
    "Export PDF": "Export PDF",
    "Select Language": "Select Language",
    "Generate": "Generate",
    "Generating...": "Generating...",
    "Analyze": "Analyze",
    "Target Goal": "Target Goal",
    "Not Set": "Not Set",
    "AI Engine": "AI Engine",
    "Ask a doubt": "Ask a doubt",
    "Search materials...": "Search materials...",
    "Download": "Download",
    "Solve": "Solve",
    "Submit": "Submit",
    "Upload": "Upload",
    "Start": "Start",
    "Close": "Close",
    "Back": "Back",
  },
  HI: {
    "Career GPS Engine": "करियर जीपीएस इंजन",
    "Study Materials Hub": "अध्ययन सामग्री हब",
    "PYQ Viewer": "PYQ दर्शक",
    "Salary Predictor": "वेतन भविष्यवक्ता",
    "Exam Directory": "परीक्षा निर्देशिका",
    "Daily Quiz": "दैनिक क्विज़",
    "Doubt Solver": "संदेह निवारक",
    "Current Affairs": "करेंट अफेयर्स",
    "Resume Rebrander": "रेज़्यूमे रीब्रांडर",
    "Roadmap Visualizer": "रोडमैप विज़ुअलाइज़र",
    "Eligibility Checker": "पात्रता चेकर",
    "Personal Vault": "व्यक्तिगत वॉल्ट",
    "Toggle Dark Mode": "डार्क मोड टॉगल करें",
    "Export PDF": "PDF निर्यात करें",
    "Select Language": "भाषा चुनें",
    "Generate": "उत्पन्न करें",
    "Generating...": "उत्पन्न हो रहा है...",
    "Analyze": "विश्लेषण करें",
    "Target Goal": "लक्ष्य",
    "Not Set": "सेट नहीं है",
    "AI Engine": "AI इंजन",
    "Ask a doubt": "एक संदेह पूछें",
    "Search materials...": "सामग्री खोजें...",
    "Download": "डाउनलोड",
    "Solve": "हल करें",
    "Submit": "जमा करें",
    "Upload": "अपलोड",
    "Start": "शुरू करें",
    "Close": "बंद करें",
    "Back": "पीछे",
  },
  TA: {
    "Career GPS Engine": "தொழில் GPS எஞ்சின்",
    "Study Materials Hub": "பொருட்கள் மையம்",
    "PYQ Viewer": "PYQ பார்வையாளர்",
    "Salary Predictor": "சம்பளம் கணிப்பான்",
    "Exam Directory": "தேர்வு அடைவு",
    "Daily Quiz": "தினசரி வினாடிவினா",
    "Doubt Solver": "சந்தேகம் தீர்ப்பவர்",
    "Current Affairs": "நடப்பு நிகழ்வுகள்",
    "Resume Rebrander": "ரெஸ்யூம் ரீபிராண்டர்",
    "Roadmap Visualizer": "வழிகாட்டல் காட்சி",
    "Eligibility Checker": "தகுதி சரிபார்ப்பு",
    "Personal Vault": "தனிப்பட்ட பெட்டகம்",
    "Toggle Dark Mode": "டார்க் மோட் மாற்றவும்",
    "Export PDF": "PDF ஏற்றுமதி",
    "Select Language": "மொழி தேர்வு",
    "Generate": "உருவாக்கு",
    "Generating...": "உருவாக்குகிறது...",
    "Analyze": "பகுப்பாய்வு செய்",
    "Target Goal": "இலக்கு",
    "Not Set": "அமைக்கப்படவில்லை",
    "AI Engine": "AI எஞ்சின்",
    "Ask a doubt": "சந்தேகம் கேள்",
    "Search materials...": "பொருட்களைத் தேடு...",
    "Download": "பதிவிறக்க",
    "Solve": "தீர்க்க",
    "Submit": "சமர்ப்பி",
    "Upload": "பதிவேற்ற",
    "Start": "தொடங்கு",
    "Close": "மூடு",
    "Back": "பின்னே",
  },
  TE: {
    "Career GPS Engine": "కెరీర్ GPS ఇంజిన్",
    "Study Materials Hub": "స్టడీ మెటీరియల్స్ హబ్",
    "PYQ Viewer": "PYQ వ్యూయర్",
    "Salary Predictor": "జీతం అంచనా",
    "Exam Directory": "పరీక్ష డైరెక్టరీ",
    "Daily Quiz": "రోజువారీ క్విజ్",
    "Doubt Solver": "సందేహాల పరిష్కారం",
    "Current Affairs": "కరెంట్ అఫైర్స్",
    "Resume Rebrander": "రెజ్యూమ్ రీబ్రాండర్",
    "Roadmap Visualizer": "రోడ్‌మ్యాప్ విజువలైజర్",
    "Eligibility Checker": "అర్హత చెకర్",
    "Personal Vault": "వ్యక్తిగత వాల్ట్",
    "Toggle Dark Mode": "డార్క్ మోడ్ మార్చు",
    "Export PDF": "PDF ఎగుమతి",
    "Select Language": "భాష ఎంచుకోండి",
    "Generate": "సృష్టించు",
    "Generating...": "సృష్టిస్తోంది...",
    "Analyze": "విశ్లేషించు",
    "Target Goal": "లక్ష్యం",
    "Not Set": "సెట్ చేయబడలేదు",
    "AI Engine": "AI ఇంజిన్",
    "Ask a doubt": "సందేహం అడగండి",
    "Search materials...": "మెటీరియల్స్ కోసం వెతకండి...",
    "Download": "డౌన్‌లోడ్",
    "Solve": "పరిష్కరించు",
    "Submit": "సమర్పించు",
    "Upload": "అప్‌లోడ్",
    "Start": "ప్రారంభించు",
    "Close": "మూసివేయు",
    "Back": "వెనక్కి",
  },
  BN: {
    "Career GPS Engine": "ক্যারিয়ার জিপিএস ইঞ্জিন",
    "Study Materials Hub": "স্টাডি ম্যাটেরিয়ালস হাব",
    "PYQ Viewer": "PYQ ভিউয়ার",
    "Salary Predictor": "বেতন নির্ধারক",
    "Exam Directory": "পরীক্ষা ডিরেক্টরি",
    "Daily Quiz": "দৈনিক কুইজ",
    "Doubt Solver": "সন্দেহ সমাধানকারী",
    "Current Affairs": "কারেন্ট অ্যাফেয়ার্স",
    "Resume Rebrander": "রিজ্যুমে রিব্র্যান্ডার",
    "Roadmap Visualizer": "রোডম্যাপ ভিজ্যুয়ালাইজার",
    "Eligibility Checker": "যোগ্যতা পরীক্ষক",
    "Personal Vault": "ব্যক্তিগত ভল্ট",
    "Toggle Dark Mode": "ডার্ক মোড টগল করুন",
    "Export PDF": "পিডিএফ রপ্তানি করুন",
    "Select Language": "ভাষা নির্বাচন করুন",
    "Generate": "তৈরি করুন",
    "Generating...": "তৈরি করা হচ্ছে...",
    "Analyze": "বিশ্লেষণ করুন",
    "Target Goal": "লক্ষ্য",
    "Not Set": "সেট করা হয়নি",
    "AI Engine": "AI ইঞ্জিন",
    "Ask a doubt": "একটি সন্দেহ জিজ্ঞাসা করুন",
    "Search materials...": "উপাদান খুঁজুন...",
    "Download": "ডাউনলোড",
    "Solve": "সমাধান করুন",
    "Submit": "জমা দিন",
    "Upload": "আপলোড",
    "Start": "শুরু করুন",
    "Close": "বন্ধ করুন",
    "Back": "পিছনে",
  },
  MR: {
    "Career GPS Engine": "करिअर जीपीएस इंजिन",
    "Study Materials Hub": "अभ्यास साहित्य हब",
    "PYQ Viewer": "PYQ दर्शक",
    "Salary Predictor": "पगार अंदाज",
    "Exam Directory": "परीक्षा निर्देशिका",
    "Daily Quiz": "दैनिक क्विझ",
    "Doubt Solver": "शंका निवारण",
    "Current Affairs": "चालू घडामोडी",
    "Resume Rebrander": "रेझ्युमे रिब्रँडर",
    "Roadmap Visualizer": "रोडमॅप व्हिज्युअलायझर",
    "Eligibility Checker": "पात्रता तपासक",
    "Personal Vault": "वैयक्तिक तिजोरी",
    "Toggle Dark Mode": "डार्क मोड टॉगल करा",
    "Export PDF": "पीडीएफ निर्यात करा",
    "Select Language": "भाषा निवडा",
    "Generate": "व्युत्पन्न करा",
    "Generating...": "व्युत्पन्न होत आहे...",
    "Analyze": "विश्लेषण करा",
    "Target Goal": "उद्दिष्ट",
    "Not Set": "सेट केलेले नाही",
    "AI Engine": "AI इंजिन",
    "Ask a doubt": "शंका विचारा",
    "Search materials...": "साहित्य शोधा...",
    "Download": "डाउनलोड करा",
    "Solve": "सोडवा",
    "Submit": "सबमिट करा",
    "Upload": "अपलोड",
    "Start": "सुरू करा",
    "Close": "बंद करा",
    "Back": "मागे",
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
