import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'EN' | 'HI' | 'TA' | 'TE' | 'BN' | 'MR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  EN: {
    "Career GPS Engine": "Career GPS Engine",
    "Study Materials Hub": "Study Materials Hub",
    "PYQ Viewer": "PYQ Viewer",
    "Salary Predictor": "Salary Predictor",
    "Exam Directory": "Exam Directory",
    "Daily Quiz": "Daily Quiz",
    "Doubt Solver": "Doubt Solver",
    "Current Affairs": "Current Affairs",
    "Resume Rebrander": "Resume Rebrander",
    "Roadmap Visualizer": "Roadmap Visualizer",
    "Eligibility Checker": "Eligibility Checker",
    "Personal Vault": "Personal Vault",
    "Toggle Dark Mode": "Toggle Dark Mode",
    "Export PDF": "Export PDF",
    "Select Language": "Select Language",
    "Generate": "Generate",
    "Generating...": "Generating...",
    "Analyze": "Analyze",
    "Target Goal": "Target Goal",
    "Not Set": "Not Set",
    "AI Engine": "AI Engine",
    "Ask a doubt": "Ask a doubt",
    "Search materials...": "Search materials...",
    "Download": "Download",
    "Solve": "Solve",
    "Submit": "Submit",
    "Upload": "Upload",
    "Start": "Start",
    "Close": "Close",
    "Back": "Back",
  },
  HI: {
    "1 Study hour logged successfully!": "1 अध्ययन घंटा सफलतापूर्वक लॉग किया गया!",
    "Weekly Career Pulse": "साप्ताहिक करियर पल्स",
    "Study Hours Logged": "अध्ययन के घंटे लॉग किए गए",
    "Quizzes Taken": "प्रश्नोत्तरी ली गई",
    "Great job! You're on track for success this week.": "बहुत बढ़िया! आप इस सप्ताह सफलता के पथ पर हैं।",
    "Keep it up! Try to hit 5 study hours and 3 quizzes this week.": "इसे जारी रखो! इस सप्ताह 5 अध्ययन घंटे और 3 क्विज़ पूरे करने का प्रयास करें।",
    "Log 1 Hour Study": "1 घंटा अध्ययन लॉग करें",
    "Save for Offline": "ऑफ़लाइन के लिए सहेजें",
    "Open Saved": "सहेजा गया खोलें",
    "Material saved for offline access!": "सामग्री को ऑफ़लाइन एक्सेस के लिए सहेजा गया!",
    "Data-driven 4-Stage Life Roadmap": "डेटा-संचालित 4-चरणीय जीवन रोडमैप",
    "Candidate": "उम्मीदवार",
    "Guest": "अतिथि",
    "Calculating optimal roadmap...": "इष्टतम रोडमैप की गणना कर रहा है...",
    "Academic Protocol": "अकादमिक प्रोटोकॉल",
    "Candidate Profile": "उम्मीदवार प्रोफाइल",
    "Full Name": "पूरा नाम",
    "Life Stage": "जीवन का चरण",
    "Find Internships": "इंटर्नशिप खोजें",
    "Exam Deadlines": "परीक्षा की समय सीमा",
    "Skill Checklist": "कौशल सूची",
    "Top Institutions Nearby": "आसपास के शीर्ष संस्थान",
    "Get Study Materials": "अध्ययन सामग्री प्राप्त करें",
    "Click to edit profile": "प्रोफाइल संपादित करने के लिए क्लिक करें",
    "No Profile Set": "कोई प्रोफाइल सेट नहीं",
    "Career GPS Engine": "करियर जीपीएस इंजन",
    "Study Materials Hub": "अध्ययन सामग्री हब",
    "PYQ Viewer": "PYQ दर्शक",
    "Salary Predictor": "वेतन भविष्यवक्ता",
    "Exam Directory": "परीक्षा निर्देशिका",
    "Daily Quiz": "दैनिक क्विज़",
    "Doubt Solver": "संदेह निवारक",
    "Current Affairs": "करेंट अफेयर्स",
    "Resume Rebrander": "रेज़्यूमे रीब्रांडर",
    "Roadmap Visualizer": "रोडमैप विज़ुअलाइज़र",
    "Eligibility Checker": "पात्रता चेकर",
    "Personal Vault": "व्यक्तिगत वॉल्ट",
    "Toggle Dark Mode": "डार्क मोड टॉगल करें",
    "Export PDF": "PDF निर्यात करें",
    "Select Language": "भाषा चुनें",
    "Generate": "उत्पन्न करें",
    "Generating...": "उत्पन्न हो रहा है...",
    "Analyze": "विश्लेषण करें",
    "Target Goal": "लक्ष्य",
    "Not Set": "सेट नहीं है",
    "AI Engine": "AI इंजन",
    "Ask a doubt": "एक संदेह पूछें",
    "Search materials...": "सामग्री खोजें...",
    "Download": "डाउनलोड",
    "Solve": "हल करें",
    "Submit": "जमा करें",
    "Upload": "अपलोड",
    "Start": "शुरू करें",
    "Close": "बंद करें",
    "Back": "पीछे",
  },
  TA: {
    "1 Study hour logged successfully!": "1 ஆய்வு மணிநேரம் வெற்றிகரமாக பதிவு செய்யப்பட்டது!",
    "Weekly Career Pulse": "வாராந்திர தொழில் துடிப்பு",
    "Study Hours Logged": "ஆய்வு நேரம் பதிவு செய்யப்பட்டது",
    "Quizzes Taken": "வினாடி வினாக்கள் எடுக்கப்பட்டன",
    "Great job! You're on track for success this week.": "நல்ல வேலை! இந்த வாரம் வெற்றிக்கான பாதையில் உள்ளீர்கள்.",
    "Keep it up! Try to hit 5 study hours and 3 quizzes this week.": "தொடர்ந்து முன்னேறுங்கள்! இந்த வாரம் 5 படிப்பு மணிநேரம் மற்றும் 3 வினாடி வினாக்களை முடிக்க முயற்சிக்கவும்.",
    "Log 1 Hour Study": "1 மணி நேரப் படிப்பைப் பதிவு செய்",
    "Save for Offline": "ஆஃப்லைனுக்கு சேமிக்கவும்",
    "Open Saved": "சேமிக்கப்பட்டதை திறக்கவும்",
    "Material saved for offline access!": "ஆஃப்லைன் அணுகலுக்கு சேமிக்கப்பட்டது!",
    "Data-driven 4-Stage Life Roadmap": "தரவு சார்ந்த 4-நிலை வாழ்க்கை வழிகாட்டி",
    "Candidate": "வேட்பாளர்",
    "Guest": "விருந்தினர்",
    "Calculating optimal roadmap...": "உகந்த வழிகாட்டியை கணக்கிடுகிறது...",
    "Academic Protocol": "கல்வி நெறிமுறை",
    "Candidate Profile": "வேட்பாளர் சுயவிவரம்",
    "Full Name": "முழு பெயர்",
    "Life Stage": "வாழ்க்கை நிலை",
    "Find Internships": "பயிற்சிகளைக் கண்டறியவும்",
    "Exam Deadlines": "தேர்வு காலக்கெடு",
    "Skill Checklist": "திறன் சரிபார்ப்பு பட்டியல்",
    "Top Institutions Nearby": "அருகிலுள்ள சிறந்த நிறுவனங்கள்",
    "Get Study Materials": "ஆய்வுப் பொருட்களைப் பெறவும்",
    "Click to edit profile": "சுயவிவரத்தைத் திருத்த கிளிக் செய்க",
    "No Profile Set": "சுயவிவரம் அமைக்கப்படவில்லை",
    "Career GPS Engine": "தொழில் GPS எஞ்சின்",
    "Study Materials Hub": "பொருட்கள் மையம்",
    "PYQ Viewer": "PYQ பார்வையாளர்",
    "Salary Predictor": "சம்பளம் கணிப்பான்",
    "Exam Directory": "தேர்வு அடைவு",
    "Daily Quiz": "தினசரி வினாடிவினா",
    "Doubt Solver": "சந்தேகம் தீர்ப்பவர்",
    "Current Affairs": "நடப்பு நிகழ்வுகள்",
    "Resume Rebrander": "ரெஸ்யூம் ரீபிராண்டர்",
    "Roadmap Visualizer": "வழிகாட்டல் காட்சி",
    "Eligibility Checker": "தகுதி சரிபார்ப்பு",
    "Personal Vault": "தனிப்பட்ட பெட்டகம்",
    "Toggle Dark Mode": "டார்க் மோட் மாற்றவும்",
    "Export PDF": "PDF ஏற்றுமதி",
    "Select Language": "மொழி தேர்வு",
    "Generate": "உருவாக்கு",
    "Generating...": "உருவாக்குகிறது...",
    "Analyze": "பகுப்பாய்வு செய்",
    "Target Goal": "இலக்கு",
    "Not Set": "அமைக்கப்படவில்லை",
    "AI Engine": "AI எஞ்சின்",
    "Ask a doubt": "சந்தேகம் கேள்",
    "Search materials...": "பொருட்களைத் தேடு...",
    "Download": "பதிவிறக்க",
    "Solve": "தீர்க்க",
    "Submit": "சமர்ப்பி",
    "Upload": "பதிவேற்ற",
    "Start": "தொடங்கு",
    "Close": "மூடு",
    "Back": "பின்னே",
  },
  TE: {
    "1 Study hour logged successfully!": "1 అధ్యయన గంట విజయవంతంగా లాగ్ చేయబడింది!",
    "Weekly Career Pulse": "వారపు కెరీర్ పల్స్",
    "Study Hours Logged": "అధ్యయన గంటలు లాగ్ చేయబడ్డాయి",
    "Quizzes Taken": "క్విజ్‌లు తీసుకోబడ్డాయి",
    "Great job! You're on track for success this week.": "గొప్ప పని! మీరు ఈ వారం విజయపథంలో ఉన్నారు.",
    "Keep it up! Try to hit 5 study hours and 3 quizzes this week.": "ఇలాగే కొనసాగించండి! ఈ వారం 5 అధ్యయన గంటలు మరియు 3 క్విజ్‌లను చేరుకోవడానికి ప్రయత్నించండి.",
    "Log 1 Hour Study": "1 గంట అధ్యయనాన్ని లాగ్ చేయండి",
    "Save for Offline": "ఆఫ్‌లైన్ కోసం సేవ్ చేయండి",
    "Open Saved": "సేవ్ చేసిన వాటిని తెరవండి",
    "Material saved for offline access!": "ఆఫ్‌లైన్ యాక్సెస్ కోసం సేవ్ చేయబడింది!",
    "Data-driven 4-Stage Life Roadmap": "డేటా ఆధారిత 4-దశల జీవిత రోడ్‌మ్యాప్",
    "Candidate": "అభ్యర్థి",
    "Guest": "అతిథి",
    "Calculating optimal roadmap...": "సరైన రోడ్‌మ్యాప్‌ను గణిస్తోంది...",
    "Academic Protocol": "విద్యా ప్రోటోకాల్",
    "Candidate Profile": "అభ్యర్థి ప్రొఫైల్",
    "Full Name": "పూర్తి పేరు",
    "Life Stage": "జీవిత దశ",
    "Find Internships": "ఇంటర్న్‌షిప్‌లను కనుగొనండి",
    "Exam Deadlines": "పరీక్ష గడువులు",
    "Skill Checklist": "స్కిల్ చెక్‌లిస్ట్",
    "Top Institutions Nearby": "సమీపంలోని అగ్ర సంస్థలు",
    "Get Study Materials": "స్టడీ మెటీరియల్స్ పొందండి",
    "Click to edit profile": "ప్రొఫైల్‌ను సవరించడానికి క్లిక్ చేయండి",
    "No Profile Set": "ప్రొఫైల్ సెట్ చేయబడలేదు",
    "Career GPS Engine": "కెరీర్ GPS ఇంజిన్",
    "Study Materials Hub": "స్టడీ మెటీరియల్స్ హబ్",
    "PYQ Viewer": "PYQ వ్యూయర్",
    "Salary Predictor": "జీతం అంచనా",
    "Exam Directory": "పరీక్ష డైరెక్టరీ",
    "Daily Quiz": "రోజువారీ క్విజ్",
    "Doubt Solver": "సందేహాల పరిష్కారం",
    "Current Affairs": "కరెంట్ అఫైర్స్",
    "Resume Rebrander": "రెజ్యూమ్ రీబ్రాండర్",
    "Roadmap Visualizer": "రోడ్‌మ్యాప్ విజువలైజర్",
    "Eligibility Checker": "అర్హత చెకర్",
    "Personal Vault": "వ్యక్తిగత వాల్ట్",
    "Toggle Dark Mode": "డార్క్ మోడ్ మార్చు",
    "Export PDF": "PDF ఎగుమతి",
    "Select Language": "భాష ఎంచుకోండి",
    "Generate": "సృష్టించు",
    "Generating...": "సృష్టిస్తోంది...",
    "Analyze": "విశ్లేషించు",
    "Target Goal": "లక్ష్యం",
    "Not Set": "సెట్ చేయబడలేదు",
    "AI Engine": "AI ఇంజిన్",
    "Ask a doubt": "సందేహం అడగండి",
    "Search materials...": "మెటీరియల్స్ కోసం వెతకండి...",
    "Download": "డౌన్‌లోడ్",
    "Solve": "పరిష్కరించు",
    "Submit": "సమర్పించు",
    "Upload": "అప్‌లోడ్",
    "Start": "ప్రారంభించు",
    "Close": "మూసివేయు",
    "Back": "వెనక్కి",
  },
  BN: {
    "1 Study hour logged successfully!": "1 অধ্যয়নের ঘন্টা সফলভাবে লগ করা হয়েছে!",
    "Weekly Career Pulse": "সাপ্তাহিক ক্যারিয়ার পালস",
    "Study Hours Logged": "অধ্যয়নের সময় লগ করা হয়েছে",
    "Quizzes Taken": "কুইজ নেওয়া হয়েছে",
    "Great job! You're on track for success this week.": "দারুণ কাজ! আপনি এই সপ্তাহে সাফল্যের পথে আছেন।",
    "Keep it up! Try to hit 5 study hours and 3 quizzes this week.": "এগিয়ে যান! এই সপ্তাহে 5 অধ্যয়নের ঘন্টা এবং 3 টি কুইজ আঘাত করার চেষ্টা করুন।",
    "Log 1 Hour Study": "1 ঘন্টা অধ্যয়ন লগ করুন",
    "Save for Offline": "অফলাইনের জন্য সংরক্ষণ করুন",
    "Open Saved": "সংরক্ষিত খুলুন",
    "Material saved for offline access!": "উপাদান অফলাইন অ্যাক্সেসের জন্য সংরক্ষিত!",
    "Data-driven 4-Stage Life Roadmap": "ডেটা-চালিত 4-পর্যায় জীবন রোডম্যাপ",
    "Candidate": "প্রার্থী",
    "Guest": "অতিথি",
    "Calculating optimal roadmap...": "সর্বোত্তম রোডম্যাপ গণনা করা হচ্ছে...",
    "Academic Protocol": "একাডেমিক প্রোটোকল",
    "Candidate Profile": "প্রার্থীর প্রোফাইল",
    "Full Name": "পুরো নাম",
    "Life Stage": "জীবনের পর্যায়",
    "Find Internships": "ইন্টার্নশিপ খুঁজুন",
    "Exam Deadlines": "পরীক্ষার সময়সীমা",
    "Skill Checklist": "দক্ষতা চেকলিস্ট",
    "Top Institutions Nearby": "আশেপাশের শীর্ষ প্রতিষ্ঠান",
    "Get Study Materials": "অধ্যয়নের উপকরণ পান",
    "Click to edit profile": "প্রোফাইল সম্পাদনা করতে ক্লিক করুন",
    "No Profile Set": "কোনো প্রোফাইল সেট করা নেই",
    "Career GPS Engine": "ক্যারিয়ার জিপিএস ইঞ্জিন",
    "Study Materials Hub": "স্টাডি ম্যাটেরিয়ালস হাব",
    "PYQ Viewer": "PYQ ভিউয়ার",
    "Salary Predictor": "বেতন নির্ধারক",
    "Exam Directory": "পরীক্ষা ডিরেক্টরি",
    "Daily Quiz": "দৈনিক কুইজ",
    "Doubt Solver": "সন্দেহ সমাধানকারী",
    "Current Affairs": "কারেন্ট অ্যাফেয়ার্স",
    "Resume Rebrander": "রিজ্যুমে রিব্র্যান্ডার",
    "Roadmap Visualizer": "রোডম্যাপ ভিজ্যুয়ালাইজার",
    "Eligibility Checker": "যোগ্যতা পরীক্ষক",
    "Personal Vault": "ব্যক্তিগত ভল্ট",
    "Toggle Dark Mode": "ডার্ক মোড টগল করুন",
    "Export PDF": "পিডিএফ রপ্তানি করুন",
    "Select Language": "ভাষা নির্বাচন করুন",
    "Generate": "তৈরি করুন",
    "Generating...": "তৈরি করা হচ্ছে...",
    "Analyze": "বিশ্লেষণ করুন",
    "Target Goal": "লক্ষ্য",
    "Not Set": "সেট করা হয়নি",
    "AI Engine": "AI ইঞ্জিন",
    "Ask a doubt": "একটি সন্দেহ জিজ্ঞাসা করুন",
    "Search materials...": "উপাদান খুঁজুন...",
    "Download": "ডাউনলোড",
    "Solve": "সমাধান করুন",
    "Submit": "জমা দিন",
    "Upload": "আপলোড",
    "Start": "শুরু করুন",
    "Close": "বন্ধ করুন",
    "Back": "পিছনে",
  },
  MR: {
    "1 Study hour logged successfully!": "१ अभ्यासाचा तास यशस्वीरित्या लॉग झाला!",
    "Weekly Career Pulse": "साप्ताहिक करिअर पल्स",
    "Study Hours Logged": "अभ्यासाचे तास लॉग केले",
    "Quizzes Taken": "क्विझ घेतल्या",
    "Great job! You're on track for success this week.": "उत्तम काम! आपण या आठवड्यात यशाच्या मार्गावर आहात.",
    "Keep it up! Try to hit 5 study hours and 3 quizzes this week.": "असेच चालू ठेवा! या आठवड्यात ५ अभ्यासाचे तास आणि ३ क्विझ पूर्ण करण्याचा प्रयत्न करा.",
    "Log 1 Hour Study": "१ तासाचा अभ्यास लॉग करा",
    "Save for Offline": "ऑफलाइनसाठी जतन करा",
    "Open Saved": "जतन केलेले उघडा",
    "Material saved for offline access!": "सामग्री ऑफलाइन प्रवेशासाठी जतन केली!",
    "Data-driven 4-Stage Life Roadmap": "डेटा-चालित 4-टप्प्यांचा जीवन रोडमॅप",
    "Candidate": "उमेदवार",
    "Guest": "अतिथी",
    "Calculating optimal roadmap...": "इष्टतम रोडमॅपची गणना करत आहे...",
    "Academic Protocol": "शैक्षणिक प्रोटोकॉल",
    "Candidate Profile": "उमेदवार प्रोफाइल",
    "Full Name": "पूर्ण नाव",
    "Life Stage": "जीवनाचा टप्पा",
    "Find Internships": "इंटर्नशिप शोधा",
    "Exam Deadlines": "परीक्षेची अंतिम मुदत",
    "Skill Checklist": "कौशल्य चेकलिस्ट",
    "Top Institutions Nearby": "जवळील शीर्ष संस्था",
    "Get Study Materials": "अभ्यास साहित्य मिळवा",
    "Click to edit profile": "प्रोफाइल संपादित करण्यासाठी क्लिक करा",
    "No Profile Set": "कोणतेही प्रोफाइल सेट केलेले नाही",
    "Career GPS Engine": "करिअर जीपीएस इंजिन",
    "Study Materials Hub": "अभ्यास साहित्य हब",
    "PYQ Viewer": "PYQ दर्शक",
    "Salary Predictor": "पगार अंदाज",
    "Exam Directory": "परीक्षा निर्देशिका",
    "Daily Quiz": "दैनिक क्विझ",
    "Doubt Solver": "शंका निवारण",
    "Current Affairs": "चालू घडामोडी",
    "Resume Rebrander": "रेझ्युमे रिब्रँडर",
    "Roadmap Visualizer": "रोडमॅप व्हिज्युअलायझर",
    "Eligibility Checker": "पात्रता तपासक",
    "Personal Vault": "वैयक्तिक तिजोरी",
    "Toggle Dark Mode": "डार्क मोड टॉगल करा",
    "Export PDF": "पीडीएफ निर्यात करा",
    "Select Language": "भाषा निवडा",
    "Generate": "व्युत्पन्न करा",
    "Generating...": "व्युत्पन्न होत आहे...",
    "Analyze": "विश्लेषण करा",
    "Target Goal": "उद्दिष्ट",
    "Not Set": "सेट केलेले नाही",
    "AI Engine": "AI इंजिन",
    "Ask a doubt": "शंका विचारा",
    "Search materials...": "साहित्य शोधा...",
    "Download": "डाउनलोड करा",
    "Solve": "सोडवा",
    "Submit": "सबमिट करा",
    "Upload": "अपलोड",
    "Start": "सुरू करा",
    "Close": "बंद करा",
    "Back": "मागे",
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
